# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'GPUImageDemo' do
  
  pod 'GPUImage'

end

target 'GPUFilter' do
    
    pod 'GPUImage'
    
end
